# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: value-schema.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='value-schema.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12value-schema.proto\"z\n\tEventtest\x12\r\n\x05Scope\x18\x01 \x01(\t\x12\x0f\n\x07Version\x18\x02 \x01(\t\x12\x0c\n\x04Name\x18\x03 \x01(\t\x1a?\n\x07Payload\x12\x16\n\x0erequired_field\x18\x01 \x01(\t\x1a\x1c\n\x0cstruct_field\x12\x0c\n\x04name\x18\x01 \x01(\tb\x06proto3'
)




_EVENTTEST_PAYLOAD_STRUCT_FIELD = _descriptor.Descriptor(
  name='struct_field',
  full_name='Eventtest.Payload.struct_field',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Eventtest.Payload.struct_field.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=144,
)

_EVENTTEST_PAYLOAD = _descriptor.Descriptor(
  name='Payload',
  full_name='Eventtest.Payload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='required_field', full_name='Eventtest.Payload.required_field', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_EVENTTEST_PAYLOAD_STRUCT_FIELD, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=144,
)

_EVENTTEST = _descriptor.Descriptor(
  name='Eventtest',
  full_name='Eventtest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Scope', full_name='Eventtest.Scope', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Version', full_name='Eventtest.Version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Name', full_name='Eventtest.Name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_EVENTTEST_PAYLOAD, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=144,
)

_EVENTTEST_PAYLOAD_STRUCT_FIELD.containing_type = _EVENTTEST_PAYLOAD
_EVENTTEST_PAYLOAD.containing_type = _EVENTTEST
DESCRIPTOR.message_types_by_name['Eventtest'] = _EVENTTEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Eventtest = _reflection.GeneratedProtocolMessageType('Eventtest', (_message.Message,), {

  'Payload' : _reflection.GeneratedProtocolMessageType('Payload', (_message.Message,), {

    'struct_field' : _reflection.GeneratedProtocolMessageType('struct_field', (_message.Message,), {
      'DESCRIPTOR' : _EVENTTEST_PAYLOAD_STRUCT_FIELD,
      '__module__' : 'value_schema_pb2'
      # @@protoc_insertion_point(class_scope:Eventtest.Payload.struct_field)
      })
    ,
    'DESCRIPTOR' : _EVENTTEST_PAYLOAD,
    '__module__' : 'value_schema_pb2'
    # @@protoc_insertion_point(class_scope:Eventtest.Payload)
    })
  ,
  'DESCRIPTOR' : _EVENTTEST,
  '__module__' : 'value_schema_pb2'
  # @@protoc_insertion_point(class_scope:Eventtest)
  })
_sym_db.RegisterMessage(Eventtest)
_sym_db.RegisterMessage(Eventtest.Payload)
_sym_db.RegisterMessage(Eventtest.Payload.struct_field)


# @@protoc_insertion_point(module_scope)
